image: node:18

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

# Define stages
stages:
  - build

# Install dependencies and build
build:
  stage: build
  script:
    - npm ci
    - npm run build